[View in Colaboratory](https://colab.research.google.com/github/suleymanbalaban3/AnswerGradingWithLSTM/blob/master/calistir.ipynb)

In [1]:
!python3 drive/LSTM/dataCrossTest.py

python3: can't open file 'drive/LSTM/dataCrossTest.py': [Errno 2] No such file or directory


In [2]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.


In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

In [0]:
import sys
sys.path.insert(0, 'drive/lstm')

In [0]:
!pip3 install -q keras

In [0]:
!pip3 install -q gensim

In [29]:
!python3 drive/LSTM/dataAllTestColabSave1.py

/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

Reading pre-trained word embeddings...
Reading text data for classification and building representations...
Reading text data for classification and building representations...
127
Number of Classes :6
Size of Train :127
Size of Test :0
----

/usr/local/lib/python3.6/dist-packages/keras/models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '
Epoch 1/64
127/127 [==============================] - 25s 199ms/step - loss: 1.5286 - acc: 0.5433
Epoch 2/64
127/127 [==============================] - 24s 188ms/step - loss: 1.2748 - acc: 0.5827
Epoch 3/64
127/127 [==============================] - 24s 189ms/step - loss: 1.2432 - acc: 0.5827
Epoch 4/64
127/127 [==============================] - 24s 191ms/step - loss: 1.2553 - acc: 0.5827
Epoch 5/64
127/127 [==============================] - 24s 192ms/step - loss: 1.2390 - acc: 0.5827
Epoch 6/64
127/127 [==============================] - 24s 190ms/step - loss: 1.2248 - acc: 0.5827
Epoch 7/64
127/127 [==============================] - 24s 191ms/step - loss: 1.2195 - acc: 0.5827
Epoch 8/64
127/127 [==============================] - 24s 191ms/step - loss: 1.1822 - acc: 0.5827
Epoch 9/64
127/127 [===========

127/127 [==============================] - 24s 189ms/step - loss: 1.0425 - acc: 0.5827
Epoch 15/64
127/127 [==============================] - 24s 189ms/step - loss: 1.0509 - acc: 0.5827
Epoch 16/64
127/127 [==============================] - 24s 187ms/step - loss: 0.9797 - acc: 0.5827
Epoch 17/64
127/127 [==============================] - 24s 188ms/step - loss: 0.9447 - acc: 0.5827
Epoch 18/64
127/127 [==============================] - 24s 188ms/step - loss: 0.9124 - acc: 0.5827
Epoch 19/64
127/127 [==============================] - 24s 187ms/step - loss: 0.8405 - acc: 0.5827
Epoch 20/64
127/127 [==============================] - 24s 190ms/step - loss: 0.7935 - acc: 0.5984
Epoch 21/64
127/127 [==============================] - 24s 188ms/step - loss: 0.7747 - acc: 0.6142
Epoch 22/64
127/127 [==============================] - 24s 189ms/step - loss: 0.6904 - acc: 0.6772
Epoch 23/64
127/127 [==============================] - 24s 188ms/step - loss: 0.6814 - acc: 0.7480
Epoch 24/64
127/127 [=

127/127 [==============================] - 24s 189ms/step - loss: 0.2317 - acc: 0.9764
Epoch 30/64
127/127 [==============================] - 24s 189ms/step - loss: 0.2065 - acc: 0.9685
Epoch 31/64
127/127 [==============================] - 24s 189ms/step - loss: 0.1820 - acc: 0.9528
Epoch 32/64
127/127 [==============================] - 24s 189ms/step - loss: 0.1555 - acc: 0.9843
Epoch 33/64
127/127 [==============================] - 24s 189ms/step - loss: 0.1318 - acc: 0.9843
Epoch 34/64
127/127 [==============================] - 24s 189ms/step - loss: 0.1173 - acc: 0.9843
Epoch 35/64
127/127 [==============================] - 24s 191ms/step - loss: 0.1216 - acc: 0.9764
Epoch 36/64
127/127 [==============================] - 24s 189ms/step - loss: 0.1166 - acc: 0.9843
Epoch 37/64
127/127 [==============================] - 24s 190ms/step - loss: 0.1008 - acc: 0.9843
Epoch 38/64
127/127 [==============================] - 24s 188ms/step - loss: 0.0861 - acc: 0.9921
Epoch 39/64
127/127 [=

127/127 [==============================] - 24s 188ms/step - loss: 0.0557 - acc: 0.9921
Epoch 45/64
127/127 [==============================] - 24s 190ms/step - loss: 0.0385 - acc: 1.0000
Epoch 46/64
127/127 [==============================] - 24s 188ms/step - loss: 0.0355 - acc: 1.0000
Epoch 47/64
127/127 [==============================] - 24s 190ms/step - loss: 0.0374 - acc: 0.9921
Epoch 48/64
127/127 [==============================] - 24s 189ms/step - loss: 0.0305 - acc: 0.9921
Epoch 49/64
127/127 [==============================] - 24s 188ms/step - loss: 0.0239 - acc: 1.0000
Epoch 50/64
127/127 [==============================] - 24s 187ms/step - loss: 0.0220 - acc: 1.0000
Epoch 51/64
127/127 [==============================] - 24s 188ms/step - loss: 0.0175 - acc: 1.0000
Epoch 52/64
127/127 [==============================] - 24s 188ms/step - loss: 0.0177 - acc: 1.0000
Epoch 53/64
127/127 [==============================] - 24s 189ms/step - loss: 0.0208 - acc: 1.0000
Epoch 54/64
127/127 [=

127/127 [==============================] - 24s 188ms/step - loss: 0.0151 - acc: 1.0000
Epoch 60/64
127/127 [==============================] - 24s 188ms/step - loss: 0.0217 - acc: 0.9921
Epoch 61/64
127/127 [==============================] - 24s 187ms/step - loss: 0.0255 - acc: 0.9921
Epoch 62/64
127/127 [==============================] - 24s 188ms/step - loss: 0.0550 - acc: 0.9843
Epoch 63/64
127/127 [==============================] - 24s 187ms/step - loss: 0.0183 - acc: 1.0000
Epoch 64/64
127/127 [==============================] - 24s 188ms/step - loss: 0.0181 - acc: 1.0000
[[  0   0   0 ...   6  19  64]
 [  0   0   0 ...   3   1  23]
 [  0   0   0 ...   1  46  23]
 ...
 [  0   0   0 ... 182 849 123]
 [  0   0   0 ...  78  11 110]
 [  0   0   0 ... 552 553 554]]
[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.

In [0]:
import keras_resnet








































































